# Read from CSV File

In [1]:
import pandas as pd

In [2]:
csv_data = pd.read_csv("data1.csv")
print(csv_data.head())

   srn      name  marks
0    1  Biswarup     98
1    2       Bob     88


In [3]:
"""
    for readig a csv file = read_csv("<filename>")
    for reading a excel file = read_excel("student.xlsx",sheet_name = 1) sheet_name is the number of sheet I want to read
"""

'\n    for readig a csv file = read_csv("<filename>")\n    for reading a excel file = read_excel("student.xlsx",sheet_name = 1) sheet_name is the number of sheet I want to read\n'

# Reading from the DataBases

In [5]:
from sqlalchemy import create_engine
import pandas as pd

In [13]:
engine = create_engine("mysql+pymysql://root:Biswarup%4012345@localhost:3306/full")
df = pd.read_sql("SELECT * FROM f", engine)
print(df.head())

      name  roll
0    Alice   101
1      Bob   102
2  Charlie   103


In [8]:
import requests

response = requests.get("https://jsonplaceholder.typicode.com/posts")

api_data = pd.DataFrame(response.json())
print(api_data)

    userId   id                                              title  \
0        1    1  sunt aut facere repellat provident occaecati e...   
1        1    2                                       qui est esse   
2        1    3  ea molestias quasi exercitationem repellat qui...   
3        1    4                               eum et est occaecati   
4        1    5                                 nesciunt quas odio   
..     ...  ...                                                ...   
95      10   96  quaerat velit veniam amet cupiditate aut numqu...   
96      10   97         quas fugiat ut perspiciatis vero provident   
97      10   98                        laboriosam dolor voluptates   
98      10   99  temporibus sit alias delectus eligendi possimu...   
99      10  100              at nam consequatur ea labore ea harum   

                                                 body  
0   quia et suscipit\nsuscipit recusandae consequu...  
1   est rerum tempore vitae\nsequi sint nihil r

In [9]:
res = requests.get("https://nse.com/")
print(res.text)

<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">
<script type="text/javascript">
/* <![CDATA[ */
(()=>{var e={};e.g=function(){if("object"==typeof globalThis)return globalThis;try{return this||new Function("return this")()}catch(e){if("object"==typeof window)return window}}(),function({ampUrl:n,isCustomizePreview:t,isAmpDevMode:r,noampQueryVarName:o,noampQueryVarValue:s,disabledStorageKey:i,mobileUserAgents:a,regexRegex:c}){if("undefined"==typeof sessionStorage)return;const d=new RegExp(c);if(!a.some((e=>{const n=e.match(d);return!(!n||!new RegExp(n[1],n[2]).test(navigator.userAgent))||navigator.userAgent.includes(e)})))return;e.g.addEventListener("DOMContentLoaded",(()=>{const e=document.getElementById("amp-mobile-version-switcher");if(!e)return;e.hidden=!1;const n=e.querySelector("a[href]");n&&n.addEventListener("click",(()=>{sessionStorage.removeIt

In [11]:
import psutil
battery = psutil.sensors_battery()
print("Battery Percentage:", battery.percent)
print("Plugged In:", battery.power_plugged)

Battery Percentage: 84
Plugged In: False


In [15]:
import cv2
cap = cv2.VideoCapture(0)
ret, frame = cap.read()
if ret:
    cv2.imwrite("webcam_snapshot.jpg", frame)
    print("Snapshot saved!")
cap.release()

Snapshot saved!


In [16]:
frame

array([[[ 3,  7,  9],
        [ 5,  9, 11],
        [ 1,  6,  7],
        ...,
        [ 6,  8,  8],
        [ 5,  7,  7],
        [ 5,  7,  7]],

       [[ 3,  7,  9],
        [ 5,  9, 11],
        [ 0,  2,  4],
        ...,
        [ 5,  7,  7],
        [ 1,  4,  3],
        [ 3,  6,  6]],

       [[ 4,  8, 10],
        [ 3,  7,  9],
        [ 4,  8, 10],
        ...,
        [ 2,  5,  4],
        [ 5,  7,  7],
        [ 3,  6,  6]],

       ...,

       [[ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  4,  3],
        ...,
        [ 0,  3,  2],
        [ 0,  3,  2],
        [ 1,  4,  3]],

       [[ 1,  1,  1],
        [ 1,  1,  1],
        [ 0,  0,  0],
        ...,
        [ 1,  4,  3],
        [ 1,  4,  3],
        [ 0,  0,  0]],

       [[ 3,  4,  3],
        [ 1,  1,  1],
        [ 1,  1,  1],
        ...,
        [ 1,  4,  3],
        [ 0,  0,  0],
        [ 0,  3,  2]]], shape=(720, 1280, 3), dtype=uint8)

In [ ]:
# import pandas as pd
# Batch Ingestion
import schedule
import time
def load_batch():
    df = pd.read_csv("batch.csv")
    print("Loaded today's batch")
    print(df.head())
schedule.every(1).minutes.do(load_batch)
while True:
    schedule.run_pending()
    time.sleep(1)

Loaded today's batch
     hat  department connection
0  white          it         up
1  black    networks         up
2   gray  blockchain       down
3    red      python         up
Loaded today's batch
     hat  department connection
0  white          it         up
1  black    networks         up
2   gray  blockchain       down
3    red      python         up
Loaded today's batch
     hat  department connection
0  white          it         up
1  black    networks         up
2   gray  blockchain       down
3    red      python         up
Loaded today's batch
     hat  department connection
0  white          it         up
1  black    networks         up
2   gray  blockchain       down
3    red      python         up
4  green         c++       down


KeyboardInterrupt: 

In [23]:
import yfinance as yf
ticker = yf.Ticker("AAPL")
import time
while True:
    price = ticker.info["currentPrice"]
    print("AAPL Current Price:",price)
    time.sleep(5)

AAPL Current Price: 198.51
AAPL Current Price: 198.51
AAPL Current Price: 198.51
AAPL Current Price: 198.51
AAPL Current Price: 198.51
AAPL Current Price: 198.51
AAPL Current Price: 198.51
AAPL Current Price: 198.51
AAPL Current Price: 198.51
AAPL Current Price: 198.51
AAPL Current Price: 198.51


KeyboardInterrupt: 

In [24]:
import requests
response = requests.get("https://www.worldometers.info/world-population/india-population")
response.text

'<!DOCTYPE html><html lang="en"> <head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><title>India Population (2025) - Worldometer</title><script async src="https://www.googletagmanager.com/gtag/js?id=G-ZDP3BFSX60"></script> <script>\n    window.dataLayer = window.dataLayer || [];\n    function gtag() {\n        dataLayer.push(arguments);\n    }\n    gtag("js", new Date());\n    gtag("config", "G-ZDP3BFSX60");\n</script><script src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3701697624350410" crossorigin="anonymous"></script> <script async src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script> <link rel="preconnect" href="https://a.pub.network/" crossorigin><link rel="preconnect" href="https://b.pub.network/" crossorigin><link rel="preconnect" href="https://c.pub.network/" crossorigin><link rel="preconnect" href="https://d.pub.network/" crossor

In [28]:
df = pd.read_html(response.text)
df[0]

/var/folders/fh/knfvlly12f53mfr4d69dnwhw0000gn/T/ipykernel_12989/713938322.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(response.text)


Year  Population Yearly % Change  Yearly Change Migrants (net)  \
0   2025  1463865525           0.89%       12929734       −495,753   
1   2024  1450935791           0.89%       12866195       −630,830   
2   2023  1438069596           0.89%       12646384       −979,179   
3   2022  1425423212           0.81%       11402759     −1,353,478   
4   2020  1402617695            1.1%       14918639        −73,806   
5   2015  1328024498           1.32%       16908587       −655,085   
6   2010  1243481564           1.49%       17761048        −50,905   
7   2005  1154676322           1.77%       19350718       −929,454   
8   2000  1057922733           1.96%       19524338       −143,960   
9   1995   960301044           2.11%       19065765        −57,297   
10  1990   864972221           2.28%       18464886         125514   
11  1985   772647793           2.37%       17058754        −89,991   
12  1980   687354025           2.37%       15208898         210914   
13  1975   611309535           2.29%       13089053         434205   
14  1970   545864268           2.18%       11144824         233782   
15  1965   490140146           2.37%       10829962       −248,299   
16  1960   435990338           2.38%        9657890         146955   
17  1955   387700887           2.29%        8284413          70393   

    Median Age  Fertility Rate  Density (P/Km²) Urban Pop %  Urban Population  \
0         28.8            1.94              492       37.1%         542742539   
1         28.4            1.96              488       36.6%         530387142   
2         28.1            1.98              484         36%         518239122   
3         27.7            1.99              479       35.5%         506304869   
4         27.0            2.05              472       34.4%         483098640   
5         25.3            2.29              447       32.3%         429069459   
6         23.6            2.60              418       30.6%         380744554   
7         22.2            2.96              388         29%         334479406   
8         21.2            3.35              356       27.5%         291350282   
9         20.3            3.65              323       26.6%         255558824   
10        19.7            4.04              291       25.7%         222296728   
11        19.3            4.43              260       24.6%         190321782   
12        18.9            4.78              231       23.4%         160941941   
13        18.4            5.20              206       21.7%         132533810   
14        18.1            5.62              184         20%         109388950   
15        18.5            5.94              165       19.1%          93493844   
16        19.2            5.92              147       18.5%          80565723   
17        19.7            5.91              130       18.6%          71958495   

   Country's Share of World Pop  World Population  India Global Rank  
0                        17.78%        8231613070                  1  
1                        17.78%        8161972572                  1  
2                        17.77%        8091734930                  1  
3                        17.77%        8021407192                  1  
4                        17.78%        7887001292                  2  
5                        17.78%        7470491872                  2  
6                        17.71%        7021732148                  2  
7                        17.53%        6586970132                  2  
8                        17.14%        6171702993                  2  
9                        16.68%        5758878982                  2  
10                       16.24%        5327803110                  2  
11                       15.87%        4868943465                  2  
12                       15.45%        4447606236                  2  
13                       15.02%        4070735277                  2  
14                       14.77%        3694683794                  2

In [29]:
# Numpy Package -> Numarical Python
import numpy as np

In [31]:
arr=np.array([1,2,3,4,5])
type(arr)

numpy.ndarray

In [41]:
arr1 = np.array([[1,2],[3,4],[5,6],[7,8]])
print(type(arr1))
print(arr1)
print(arr1.shape)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [37]:
l1 = range(1,10,2)
arr = np.array(l1)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr.shape # (5, ) -> _ , _ -> how many elements you have

(5,)

In [43]:
print(type(frame))
print(frame.shape)

<class 'numpy.ndarray'>
(720, 1280, 3)


In [44]:
# Indexing
arr1 = np.array([2, 3 , 40, 60])
arr1

array([ 2,  3, 40, 60])

In [63]:
# [start, stop, step] = [0:2,:]

a = np.array([[3,5],[6,7],[8,9]])
print(a)
# print(a)

a[0:2:, : : ]

a[1:3:, 1:2:]

[[3 5]
 [6 7]
 [8 9]]


array([[7],
       [9]])

In [64]:
a[:][:]

array([[3, 5],
       [6, 7],
       [8, 9]])